apiVersion: v1
data:
  init.sql: |
    CREATE TABLE "dogdata"
    (
        id SERIAL PRIMARY KEY,
        name varchar(50) NOT NULL UNIQUE,
        breed varchar(50) NOT NULL
    );
kind: ConfigMap
metadata:
  name: {{ include "dogdataPostgres.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
