apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dogdata.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "dogdata.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dogdata.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dogdata.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dogdata.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.ports.grpc }}
              protocol: TCP
            - name: grpc-gateway
              containerPort: {{ .Values.ports.grpcGateway }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/healthcheck/livenessProbe
              port: grpc-gateway
          readinessProbe:
            httpGet:
              path: /v1/healthcheck/readinessProbe
              port: grpc-gateway
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgresConfig.host }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgresConfig.port }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresConfig.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresConfig.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresConfig.db }}
            - name: GRPC_ADDR
              value: {{ .Values.ports.grpc }}
            - name: GRPC_GATEWAY_ADDR
              value: {{ .Values.ports.grpcGateway }}
            - name: DD_SERVICE
              value: dogdata
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          {{- with .Values.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
