apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dogdata.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Mi
