apiVersion: v1
kind: Service
metadata:
  name: {{ include "dogdata.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "dogdata.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.grpcGateway }}
      targetPort: grpc-gateway
      protocol: TCP
      name: grpc-gateway
    - port: {{ .Values.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "dogdata.selectorLabels" . | nindent 4 }}
