version: "3.8"
services:
  api:
    build:
      context: .
    ports:
      - 50050:50050
      - 50051:50051
    environment:
      POSTGRES_HOST: postgres # match service name of postgres.
      POSTGRES_PORT: 5432
      POSTGRES_USER: dogdata
      POSTGRES_PASSWORD: dogdata
      POSTGRES_DB: dogdata
      GRPC_ADDR: 50050
      GRPC_GATEWAY_ADDR: 50051
      DD_SERVICE: dogdata
    networks:
      - default
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: dogdata
      POSTGRES_PASSWORD: dogdata
      POSTGRES_DB: dogdata
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
