apiVersion: v1
kind: Service
metadata:
  name: {{ include "dogdata.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    {{- include "dogdata.selectorLabels" . | nindent 6 }}
